export const HOME = '/'
export const PROGRAM = '/program'
export const SPORT = '/sport'
export const NAHRAVKY = '/nahravky'
export const DETSKE = '/detske'
export const PREMIUM = '/premium'
export const VIDEOTEQUE = '/videoteque'
